import { Filter } from '../types';

export const FILTERS: Filter[] = [
  {
    id: 'grayscale',
    name: 'Grayscale',
    description: 'Convert to black and white',
    thumbnail: '⚫',
    category: 'color',
    cssFilter: 'grayscale(100%)',
  },
  {
    id: 'sepia',
    name: 'Sepia',
    description: 'Vintage warm tone effect',
    thumbnail: '🟤',
    category: 'color',
    cssFilter: 'sepia(100%)',
  },
  {
    id: 'blur',
    name: 'Blur',
    description: 'Blur the video',
    thumbnail: '🌫️',
    category: 'blur',
    cssFilter: 'blur(5px)',
    parameters: [
      {
        name: 'intensity',
        type: 'range',
        default: 5,
        min: 0,
        max: 20,
        step: 1,
      },
    ],
  },
  {
    id: 'sharpen',
    name: 'Sharpen',
    description: 'Enhance image sharpness',
    thumbnail: '🔪',
    category: 'adjustment',
    cssFilter: 'contrast(120%) brightness(105%)',
  },
  {
    id: 'vintage',
    name: 'Vintage',
    description: 'Old film camera look',
    thumbnail: '📷',
    category: 'artistic',
    cssFilter: 'sepia(50%) contrast(110%) brightness(90%)',
  },
  {
    id: 'cool',
    name: 'Cool Tone',
    description: 'Blue-tinted cool effect',
    thumbnail: '❄️',
    category: 'color',
    cssFilter: 'hue-rotate(180deg) saturate(120%)',
  },
  {
    id: 'warm',
    name: 'Warm Tone',
    description: 'Orange-tinted warm effect',
    thumbnail: '🔥',
    category: 'color',
    cssFilter: 'sepia(30%) saturate(140%) hue-rotate(-10deg)',
  },
  {
    id: 'high-contrast',
    name: 'High Contrast',
    description: 'Boost contrast dramatically',
    thumbnail: '⚡',
    category: 'adjustment',
    cssFilter: 'contrast(150%)',
  },
  {
    id: 'vignette',
    name: 'Vignette',
    description: 'Darken edges for focus',
    thumbnail: '🎯',
    category: 'artistic',
    cssFilter: 'brightness(90%) contrast(110%)',
  },
  {
    id: 'saturate',
    name: 'Vivid',
    description: 'Increase color saturation',
    thumbnail: '🌈',
    category: 'color',
    cssFilter: 'saturate(200%)',
  },
  {
    id: 'invert',
    name: 'Invert',
    description: 'Invert all colors',
    thumbnail: '🔄',
    category: 'special',
    cssFilter: 'invert(100%)',
  },
  {
    id: 'brightness',
    name: 'Bright',
    description: 'Increase brightness',
    thumbnail: '☀️',
    category: 'adjustment',
    cssFilter: 'brightness(130%)',
    parameters: [
      {
        name: 'value',
        type: 'range',
        default: 130,
        min: 50,
        max: 200,
        step: 10,
      },
    ],
  },
];

export const FILTER_CATEGORIES = [
  { id: 'all', name: 'All Filters', icon: '🎨' },
  { id: 'color', name: 'Color', icon: '🎨' },
  { id: 'blur', name: 'Blur', icon: '🌫️' },
  { id: 'artistic', name: 'Artistic', icon: '🖼️' },
  { id: 'adjustment', name: 'Adjustments', icon: '⚙️' },
  { id: 'special', name: 'Special FX', icon: '✨' },
];
